### ISSUE TITLE
how to load pretrained model?

### ISSUE THREAD

**Issue by paulcx** [mingruimingrui/torch-collections#24]
any idea?

**Comment by mingruimingrui** [comment]
Hi @paulcx sorry for the lateness of my reply.
I'd recommend installing this package and load models with `torch.load`

Clone this repo and do `python setup.py install`

You can download a model from https://github.com/mingruimingrui/torch-collections/releases/tag/0.4b

And simply use `model = torch.load('model.pth')` to load your model.

Hope this helps!
